### ISSUE TITLE
Atomes dans la grammaire française

### ISSUE THREAD

**Issue by PatWg** [PseuToPy/PseuToPy#41]
Certains atomes ont été modifiés dans la grammaire entraînant l'impossibilité d'utiliser les mots-clés de Python avec PseuToPy.

J'ai vu : `Vrai`, `Faux`, `Vide`
Qui devraient rester : `True`, `False`, `None`.

Il y en a peut-être d'autres, mais il faudrait garder la grammaire Python intacte lorsque l'on y apporte des modifications.

**Comment by StepManlau** [comment]
correction mise en place dans la branche feat/ptp-011

**Comment by PatWg** [comment]
On s'est probablement mal compris, mais il devrait y avoir à la fois la version Python (`True`, `False`, `None`), et la version traduite (`vrai`, `faux, `vide`).

Cela laisse donc la possibilité d'écrire en PseuToPy français, mais aussi de mélanger les instructions avec du _vrai_ Python.

**Comment by StepManlau** [comment]
dans ce cas dans les possibilités 
je mets la langue du fichier lark et anglaise ?

**Comment by PatWg** [comment]
Pour donner un exemple, on devrait avoir :
```
atom:
     // ...
    | ("None" | "vide")   -> const_none
    | ("True" | "vrai")      -> const_true
    | ("False" | "faux")    -> const_false
```

Ensuite, il faudra donc laisser à chaque fois la grammaire initiale *intacte* et simplement *ajouter* les règles pour le français.

On pourra revoir ça peut-être demain du coup si tu veux.

**Comment by StepManlau** [comment]
ça marche
